// <auto-generated />
using System;
using DesafioUmHelp.WebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioUmHelp.WebApi.Migrations
{
    [DbContext(typeof(UmHelpContext))]
    [Migration("20200312044722_UmHelp")]
    partial class UmHelp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioUmHelp.WebApi.Domain.Descontos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("BIT");

                    b.Property<int>("IdUsuario");

                    b.Property<int?>("IdUsuarios");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarios");

                    b.ToTable("DescontosDeProdutos");
                });

            modelBuilder.Entity("DesafioUmHelp.WebApi.Domain.Pedidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATETIME");

                    b.Property<int>("IdProduto");

                    b.Property<int>("IdUsuarios");

                    b.Property<decimal>("ValorProduto")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdUsuarios");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("DesafioUmHelp.WebApi.Domain.Produtos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeProduto")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("DesafioUmHelp.WebApi.Domain.TiposUsuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titulo")
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.ToTable("TiposUsuarios");
                });

            modelBuilder.Entity("DesafioUmHelp.WebApi.Domain.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("IdTiposUsuarios");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DesafioUmHelp.WebApi.Domain.Descontos", b =>
                {
                    b.HasOne("DesafioUmHelp.WebApi.Domain.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuarios");
                });

            modelBuilder.Entity("DesafioUmHelp.WebApi.Domain.Pedidos", b =>
                {
                    b.HasOne("DesafioUmHelp.WebApi.Domain.Produtos", "Produtos")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DesafioUmHelp.WebApi.Domain.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuarios")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DesafioUmHelp.WebApi.Domain.Usuarios", b =>
                {
                    b.HasOne("DesafioUmHelp.WebApi.Domain.TiposUsuarios", "TiposUsuarios")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
